In [2]:
from modules.global_warming.py import global_warming_status as gws

gws

The globe is heating up!


ModuleNotFoundError: No module named 'modules.global_warming.py'; 'modules.global_warming' is not a package

In [ ]:
import sys
sys.argv?

In [11]:
nums = [0,1,2,3,4,5,6,7,8,9]
print(nums[-1:-1])
print(nums[-1:])
print(nums[::-1])
print(nums[::2])
print(nums[:-1:2])

print([0,1,2][::2])
print([0,1,2][:-1:2])

[]
[9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
[0, 2]
[0]


In [5]:
import numpy as np

a = np.array([[1,20,30,40],
             [2,20,30,40],
             [3,20,30,40]])
print(a, "\n")
print(a[True], "\n")
print(a[1], "\n")
print(a[a[:,0] == 3], "\n")
print(a[a[:,0] == 3], "\n")

# using True as a mask to get all values dumps them inside a new layer of a list. Well that sucks.

[[ 1 20 30 40]
 [ 2 20 30 40]
 [ 3 20 30 40]] 

[[[ 1 20 30 40]
  [ 2 20 30 40]
  [ 3 20 30 40]]] 

[ 2 20 30 40] 

[[ 3 20 30 40]] 

