### Class exercise: table
![](../../images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation

In [22]:
import numpy as np

a = np.arange(10, 30).reshape(4, 5)
print(a)

yellow = a[0, 0]
red = a[0, 1:4]
teal = a[:, 1::2]
green = a[:-1, 2]
blue = a[::2, -1]

print("\nyellow:", yellow, "\nred:", red, "\nteal:\n", teal, "\ngreen:", green, "\nblue:", blue)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

yellow: 10 
red: [11 12 13] 
teal:
 [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
green: [12 17 22] 
blue: [14 24]


## 3D
#### reshape can be done with multiple dimensions. Here is an example with 3d  
`a = np.arange(0, 27).reshape((3, 3, 3))`  
![](../../images/cube.png)

### Class exercise: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [36]:
a = np.arange(0,27).reshape(3,3,3)
print(a)

slice1 = a[1, 1, :]
slice2 = a[:, 1, 0]
slice3 = a[0, :, 2]
print("\n")
print(slice1)
print(slice2)
print(slice3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[12 13 14]
[ 3 12 21]
[2 5 8]


In [38]:
# assign value to multiple cells, for fun
b = a.copy()
print(b)
print("\n")
b[:, 1] = 99
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[[[ 0  1  2]
  [99 99 99]
  [ 6  7  8]]

 [[ 9 10 11]
  [99 99 99]
  [15 16 17]]

 [[18 19 20]
  [99 99 99]
  [24 25 26]]]


In [34]:
c = np.empty((3, 3, 3), dtype=int)
c[:] = 99
print(c)

[[[99 99 99]
  [99 99 99]
  [99 99 99]]

 [[99 99 99]
  [99 99 99]
  [99 99 99]]

 [[99 99 99]
  [99 99 99]
  [99 99 99]]]


### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6

In [47]:
data = np.arange(1,101).reshape(10,10)

evens = data % 2 == 0
print(evens)
print(data[evens], "\n")

sixes = np.where(data % 10 == 6)
print(sixes)
print(data[sixes])

[[False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100] 

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))
[ 6 16 26 36 46 56 66 76 86 96]
