### Class exercise: table
![](../../images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation

In [22]:
import numpy as np

a = np.arange(10, 30).reshape(4, 5)
print(a)

yellow = a[0, 0]
red = a[0, 1:4]
teal = a[:, 1::2]
green = a[:-1, 2]
blue = a[::2, -1]

print("\nyellow:", yellow, "\nred:", red, "\nteal:\n", teal, "\ngreen:", green, "\nblue:", blue)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

yellow: 10 
red: [11 12 13] 
teal:
 [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
green: [12 17 22] 
blue: [14 24]


## 3D
#### reshape can be done with multiple dimensions. Here is an example with 3d  
`a = np.arange(0, 27).reshape((3, 3, 3))`  
![](../../images/cube.png)

### Class exercise: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [21]:
a = np.arange(0,27).reshape(3,3,3)
print(a)

slice1 = a[1, 1, :]
slice2 = a[:, 1, 0]
slice3 = a[0, :, 2]
print("\n")
print(slice1)
print(slice2)
print(slice3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[12 13 14]
[ 3 12 21]
[2 5 8]
